global:
  scrape_interval: 15s

scrape_configs:
  - job_name: fraudlatch-api
    static_configs:
      - targets: ["host.docker.internal:8000"]
  - job_name: fraudlatch-worker
    static_configs:
      - targets: ["host.docker.internal:8001"]
